### ISSUE TITLE
doesn't work with RN >= v0.29.0

### ISSUE THREAD

**Issue by theaidem** [rupliva/react-native-dimmer#4]
```
path/to/project/android/app/src/main/java/com/starterkit/MainActivity.java:23: error:
 method does not override or implement a method from a supertype                                          
    @Override                                                                                             
    ^
...                                                                                                     
```
I found the same error
http://stackoverflow.com/questions/38843385/method-does-not-override-or-implement-a-method-from-a-supertype-appcompiledeb
but if I moves `new ReactNativeDimmerPackage(this)` in MainApplication.java

```
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new ReactNativeDimmerPackage(this)
      );
    }

  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

I've got another error

> incompatible types: <anonymous ReactNativeHost> cannot be converted to Activity

Do you have any ideas how to solve this? Thanks

**Comment by netgusto** [comment]
@theaidem Use this package, works fine : https://github.com/corbt/react-native-keep-awake
